# Title for your page
# title: Put Your Title Here

# Description for your page
# description: "Your Title Here is a blah blah blah"

# Theme -- dark light or auto
css: auto

# Show downloads links -- true or false 
show_downloads: true

# Not using GitHub? Change this value to what you want it to say.
git_provider: GitHub

# Different Download link?
# download_url: "https://example.com"

# Goatcounter site code
# goatcounter: myproject
