# Title for your page
title: Put A Title Here

# Description for your page
description: "a nice description or tagline"

# Theme -- dark light or auto
css: auto

# Show downloads links -- True or false 
show_downloads: true

# Not using GitHub? Change this.
git_provider: GitHub

#Different Download link?
#download_url: "https://example.com"

