# Title for your page
title: Put Your Title Here

# Description for your page
description: "A Great Project has a lot of description needed"

# Theme -- dark light or auto
css: auto

# Show downloads links -- True or false 
show_downloads: true

# Not using GitHub? Change this.
git_provider: GitHub

#Different Download link?
#download_url: "https://example.com"

#Goatcounter Tracking Code
#goatcounter: myproject
